<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarreraRepository extends EntityRepository
{
    public function findCarreras()
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('c.nombre')
            ->from('AppBundle:Carrera', 'c');

        return $dql->getQuery()->getResult();
    }
}
