<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
	public function findEquipos()
	{
		$em = $this->getEntityManager();
		$dql = $em->createQueryBuilder();
		$dql->select('e.nombre equipo', "concat(ase.nombre, ' ', ase.apellidoPaterno) asesor", 'r.nombre robot', "concat(alu.nombre, ' ', alu.apellidoPaterno, ' - ', alu.correoElectronico) alumno")
		    ->from('AppBundle:Equipo', 'e')
            ->innerJoin('e.asesor', 'ase')
            ->innerJoin('e.robot', 'r')
            ->innerJoin('e.alumnos', 'alu');
		return $dql->getQuery()->getResult();
	}
}
