<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
	public function findEquipos()
	{
		$em = $this->getEntityManager();
		$dql = $em->createQueryBuilder();
		$dql->select('e.nombre')
		    ->from('AppBundle:Robot', 'e');

		return $dql->getQuery()->getResult();
	}
}
