<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RobotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RobotRepository extends EntityRepository
{
    public function findRobots()
    {
        $em = $this->getEntityManager();
        $dql = $em->createQueryBuilder();
        $dql->select('r.nombre')
            ->from('AppBundle:Robot', 'r');

        return $dql->getQuery()->getResult();
    }
}
