easy_admin:
    site_name: 'Club de robótica'
    formats:
      date: 'd/m/Y'
    design:
      color_scheme: 'dark'
      brand_color: '#f44336'
      form_theme: 'horizontal'
    list:
        max_results: 10
        actions:
            - { name: 'show', label: '', icon: 'search'}
            - { name: 'edit', label: '', icon: 'pencil' }
            - { name: 'delete', label: '', icon: 'trash' }
            - { name: 'search', label: 'Búsqueda' }
    show:
        actions:
            - { name: 'edit', label: 'Actualizar' }
            - { name: 'list', label: 'Regresar al menu' }
    edit:
        actions:
            - { name: 'list', label: 'Regresar al menú' }
    new:
        actions:
            - { name: 'list', label: 'Regresar al menú' }       
    entities:
        Alumno:
            label: 'Alumnos'
            class: AppBundle\Entity\Alumno
            list:
                title: "Alumnos"
                actions: [{ name: 'new', label: 'Agregar Alumno' }]
                fields:
                  - { property: 'id', label: 'ID' }
                  - { property: 'nombre', label: 'Nombre' }
                  - { property: 'apellidoPaterno', label: 'Apellido Paterno' }
                  - { property: 'apellidoMaterno', label: 'Apellido Materno' }
                  - { property: 'correo_electronico', type: 'email', label: 'Correo electrónico' }
                  - { property: 'semestre', label: 'Semestre' }
                  - { property: 'carrera', label: 'Carrera' }
                  - { property: 'capitan', label: 'Capitan' }
            form:
                fields:
                  - { property: 'nombre', label: 'Nombre' }
                  - { property: 'apellidoPaterno', label: 'Apellido Paterno' }
                  - { property: 'apellidoMaterno', label: 'Apellido Materno' }
                  - { property: 'correo_electronico', type: 'email', label: 'Correo electrónico', type_options: { required: true } }
                  - { property: 'semestre', label: 'Semestre' }
                  - { property: 'carrera', label: 'Carrera', type_options: { required: true } }
                  - { property: 'capitan', label: 'Capitan' }
        Asesor:
            label: 'Asesores'
            class: AppBundle\Entity\Asesor
            list:
                title: "Asesores"
                actions: [{ name: 'new', label: 'Agregar Asesor' }]
                fields:
                  - { property: 'id', label: 'ID' }
                  - { property: 'nombre', label: 'Nombre' }
                  - { property: 'apellidoPaterno', label: 'Apellido Paterno' }
                  - { property: 'apellidoMaterno', label: 'Apellido Materno' }
                  - { property: 'correo_electronico', type: 'email', label: 'Correo electrónico' }
            form:
                fields:
                  - { property: 'nombre', label: 'Nombre' }
                  - { property: 'apellidoPaterno', label: 'Apellido Paterno' }
                  - { property: 'apellidoMaterno', label: 'Apellido Materno' }
                  - { property: 'correo_electronico', type: 'email', label: 'Correo electrónico', type_options: { required: true } }
        Carrera:
            label: 'Carreras'
            class: AppBundle\Entity\Carrera
            list:
                title: "Carreras"
                actions: [{ name: 'new', label: 'Agregar Carrera' }]
                fields:
                  - { property: 'id', label: 'ID' }
                  - { property: 'nombre', label: 'Nombre' }
            form:
                fields:
                  - { property: 'nombre', label: 'Nombre' }
        Equipo:
            label: 'Equipos'
            class: AppBundle\Entity\Equipo
            list:
                title: "Equipos"
                actions: [{ name: 'new', label: 'Agregar Equipo' }]
                fields:
                  - { property: 'id', label: 'ID' }
                  - { property: 'nombre', label: 'Nombre' }
                  - { property: 'asesor', label: 'Asesor' }
                  - { property: 'robot', label: 'Robot' }
                  - { property: 'alumnos', label: 'Alumno' }
        Robot:
            label: 'Robot'
            class: AppBundle\Entity\Robot
            list:
                title: "Robot"
                actions: [{ name: 'new', label: 'Agregar Robot' }]
                fields:
                  - { property: 'id', label: 'ID' }
                  - { property: 'nombre', label: 'Nombre' }
            form:
                fields:
                  - { property: 'nombre', label: 'Nombre' }