app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

asesor_rest:
    type: rest
    resource: AppBundle\Controller\AsesorRestController
    prefix: /api/

carrera_rest:
    type: rest
    resource: AppBundle\Controller\CarreraRestController
    prefix: /api/

equipo_rest:
    type: rest
    resource: AppBundle\Controller\EquipoRestController
    prefix: /api/